"""penentuan_kelas table

Revision ID: 20c23f1ce2c4
Revises: 6c75f6b80da3
Create Date: 2018-07-28 08:57:29.549647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20c23f1ce2c4'
down_revision = '6c75f6b80da3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('penentuan_kelas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=200), nullable=True),
    sa.Column('function', sa.String(length=200), nullable=True),
    sa.Column('tweet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tweet_id'], ['tweet.id'], name=op.f('fk_penentuan_kelas_tweet_id_tweet')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_penentuan_kelas'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('penentuan_kelas')
    # ### end Alembic commands ###
