"""preprocess table

Revision ID: 3dd0d7b211ab
Revises: 0147ed47b70e
Create Date: 2018-07-28 04:12:10.082833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dd0d7b211ab'
down_revision = '0147ed47b70e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preprocess',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=200), nullable=True),
    sa.Column('tweet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tweet_id'], ['tweet.id'], name=op.f('fk_preprocess_tweet_id_tweet')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_preprocess'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('preprocess')
    # ### end Alembic commands ###
