"""postag table

Revision ID: 6c75f6b80da3
Revises: 3dd0d7b211ab
Create Date: 2018-07-28 07:33:35.132091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c75f6b80da3'
down_revision = '3dd0d7b211ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=200), nullable=True),
    sa.Column('tweet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tweet_id'], ['tweet.id'], name=op.f('fk_postag_tweet_id_tweet')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_postag'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('postag')
    # ### end Alembic commands ###
