"""grammar story table

Revision ID: f834985222c6
Revises: e7e13f584716
Create Date: 2018-07-28 09:38:37.013233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f834985222c6'
down_revision = 'e7e13f584716'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grammar_story',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.Integer(), nullable=True),
    sa.Column('sentence', sa.String(length=1000), nullable=True),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], name=op.f('fk_grammar_story_test_id_test')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grammar_story'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grammar_story')
    # ### end Alembic commands ###
